# put your secret values and credentials here. do not share this file and do not push it to github
# this file should be included in .gitignore if using sensitive info

api_secret_key = "api_secret_key" # please set me up!

[destination.filesystem]
bucket_url = "file://destiny_pii_data"

[destination.filesystem.credentials]
aws_access_key_id = "aws_access_key_id" # please set me up!
aws_secret_access_key = "aws_secret_access_key" # please set me up!

[sources.sql_database.credentials]
drivername = "postgresql+psycopg2" # please set me up!
database = "postgres" # please set me up!
password = "mysecretpassword" # please set me up!
username = "postgres" # please set me up!
host = "localhost" # please set me up!
port = 5432 # please set me up!
